apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: scrape-kube-state-metrics
spec:
  endpoints:
  - path: /metrics
    port: http-metrics
    scheme: http
    interval: 1s
    tlsConfig:
      caFile: /etc/vm/secrets/pki-vm-agent-client/ca.crt
      certFile: /etc/vm/secrets/pki-vm-agent-client/tls.crt
      keyFile: /etc/vm/secrets/pki-vm-agent-client/tls.key
      serverName: kube-state-metrics
  jobLabel: kube-state-metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
