---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "pki-prometheus-adapter-server-client"
spec:
  commonName: "system:prometheus-adapter"
  secretName: "pki-prometheus-adapter-server-client"
  duration: 8760h # 365d
  renewBefore: 4380h # 178d
  subject:
    organizations:
    - "cluster-2"
  usages:
  - "signing"
  - "key encipherment"
  - "client auth"
  - "server auth"
  issuerRef:
    name: "issuer"
    kind: Issuer