---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vmcluster
spec:
  retentionPeriod: "1"
  vmstorage:
    replicaCount: 2
  vmselect:
    serviceSpec:
      spec:
        type: ClusterIP
    replicaCount: 2
  vminsert:
    replicaCount: 2
