---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent-main
spec:
  selectAllByDefault: true
  replicaCount: 1
  secrets:
      - pki-vm-agent-client
  remoteWrite:
    - url: "http://vminsert-example-vmcluster:8480/insert/0/prometheus/api/v1/write"
