{{- $baseName         := include "kube-scheduler.name" . -}}
{{- $selectorLabels   := include "kube-scheduler.selectorLabels" . -}}
{{- $commonLabels     := include "kube-scheduler.labels" . -}}

{{- with .Values.applications.kubeScheduler.Deployment }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $baseName }}-svc
  labels:
    {{- $commonLabels | nindent 4 }}
  {{- with .metadata.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .metadata.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  loadBalancerIP:
  {{- with .containers.kubeScheduler.ports }}
  ports:
    {{- range $service := . }}
    - name: {{ $service.name }}
      port: {{ $service.containerPort }}
    {{- end }}
  {{- end }}
  selector:
    {{ $selectorLabels | nindent 4 }}
{{- end }}
