
{{- $baseName         := include "konnectivity.name" . -}}
{{- $selectorLabels   := include "konnectivity.selectorLabels" . -}}
{{- $commonLabels     := include "konnectivity.labels" . -}}
{{- $currentNamespace := .Release.Namespace -}}
{{- $konnectivityServerReplicas := $.Values.applications.konnectivityServer.replicas  }}

{{- with $.Values.applications.konnectivityServer }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $baseName }}-server"
  labels:
    {{- $commonLabels | nindent 4 }}
    {{- with .labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .replicas }}

  {{- with .strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  selector:
    matchLabels:
      {{- $selectorLabels | nindent 6 }}

  template:
    metadata:
      labels:
        {{- $commonLabels | nindent 8 }}
        {{- with .labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

    spec:
  
      {{ with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: {{ .affinity.topologyKey}}
                labelSelector:
                  matchLabels:
                    {{- $selectorLabels | nindent 20 }}

      automountServiceAccountToken: {{ .automountServiceAccountToken }}

      containers:
        {{- with .containers.konnectivityServer }}
        - name: {{ $baseName }}-server
          image: {{ .image }}
          imagePullPolicy: {{ .imagePullPolicy }}

          {{ with .resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{ with .ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{ with .envs }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          
          volumeMounts:
            - mountPath: /pki/apiserver
              name: pki-apiserver
            - mountPath: /pki/{{ $baseName }}-server
              name: pki-{{ $baseName }}server
            - mountPath: /pki/{{ $baseName }}-server-client
              name: pki-{{ $baseName }}-server-client
            - mountPath: /etc/kubernetes/
              name: kubeconfig
              readOnly: true
            {{- with .custom }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

          command: {{ .entryPoint.command }}
          args:
            - --server-ca-cert=/pki/{{ $baseName }}-server/ca.crt
            - --server-cert=/pki/{{ $baseName }}-server/tls.crt
            - --server-key=/pki/{{ $baseName }}-server/tls.key
            - --cluster-cert=/pki/apiserver/tls.crt
            - --cluster-key=/pki/apiserver/tls.key
            - --agent-service-account={{ $baseName }}-agent
            - --kubeconfig=/etc/kubernetes/{{ $baseName }}-server.conf
            - --authentication-audience=system:{{ $baseName }}-server
            - --server-count={{- $konnectivityServerReplicas }}
            {{- range .ports  }}
              {{- if eq .name "server" }}
            - --server-port={{- .containerPort }}
              {{- end }}
              {{- if eq .name "agent" }}
            - --agent-port={{- .containerPort }}
              {{- end }}
              {{- if eq .name "admin" }}
            - --admin-port={{- .containerPort }}
              {{- end }}
              {{- if eq .name "health" }}
            - --health-port={{- .containerPort }}
              {{- end }}
            {{- end }}
            {{- with .entryPoint.args }}
            {{- toYaml . | nindent 12 }}
            {{- end }}

          {{ with .livenessProbe }}
          livenessProbe:
            failureThreshold: {{ .failureThreshold  }}
            initialDelaySeconds: {{ .initialDelaySeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            {{ .method }}:
              path: {{ .path }}
              {{- range .ports  }}
                {{- if eq .name "health" }}
              port: {{ .containerPort }}
                {{- end }}
              {{- end }}
              scheme: HTTP
          {{- end }}
        {{- end }}

      volumes:
        - secret:
            secretName: "pki-apiserver-server"
          name: pki-apiserver
        - secret:
            secretName: "pki-{{ $baseName }}-server"
          name: pki-{{ $baseName }}server
        - secret:
            secretName: "pki-{{ $baseName }}-server-client"
          name: pki-{{ $baseName }}-server-client
        - configMap:
            name: "{{ $baseName }}-server-conf"
          name: kubeconfig
        {{- with .volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

{{- end}}