{{- if .Values.applications.apiProxy.enable }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-proxy-config
data:
  kube-apiserver.conf: |
    access_log /etc/nginx/nginx-access.log ;
    error_log /etc/nginx/nginx-error.log ;

    upstream kube-apiserver {
      server kube-apiserver-svc:6443;
    }

    upstream prometheus-adapter {
      server custom-metrics-apiserver:443;
    }

    server {
      listen       6443 ssl;
      listen       [::]:6443 ssl;
      ssl_certificate "/pki/server/tls.crt";
      ssl_certificate_key "/pki/server/tls.key";

      location / {
          location /apis {
            proxy_pass https://kube-apiserver;
            proxy_ssl_certificate     /pki/client/tls.crt;
            proxy_ssl_certificate_key /pki/client/tls.key;
            proxy_send_timeout 150;
            proxy_read_timeout 150;
  
          }
          location /apis/metrics.k8s.io/v1beta1 {
              proxy_pass https://prometheus-adapter;
              proxy_send_timeout 150;
              proxy_read_timeout 150;

          }
        proxy_pass https://kube-apiserver;
        proxy_ssl_certificate     /pki/client/tls.crt;
        proxy_ssl_certificate_key /pki/client/tls.key;
      }
    }
{{- end }}