---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "selfsigning-issuer"
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "issuer"
spec:
  ca:
    secretName: "pki-ca"

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "pki-ca"
spec:
  commonName: "ca"
  secretName: "pki-ca"
  duration: 87600h # 3650d
  renewBefore: 8760h # 365d
  subject:
    organizations:
      - {{ .Release.Namespace }}
  usages:
    - "signing"
    - "key encipherment"
    - "server auth"
    - "client auth"
  isCA: true
  issuerRef:
    name: "selfsigning-issuer"
    kind: Issuer

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "pki-sa"
spec:
  commonName: "sa"
  secretName: "pki-sa"
  duration: 87600h # 3650d
  renewBefore: 8760h # 365d
  subject:
    organizations:
    - {{ .Release.Namespace }}
  usages:
    - "signing"
    - "key encipherment"
    - "cert sign"
  isCA: true
  issuerRef:
    name: "selfsigning-issuer"
    kind: Issuer

