apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: kube-apiserver
    app.kubernetes.io/name: kube-apiserver
  name: kubernetes-apiserver
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: false
  ports:
    - name: client
      port: 6443
      protocol: TCP
      targetPort: client
  selector:
    app.kubernetes.io/instance: kube-apiserver
    app.kubernetes.io/name: kube-apiserver
  sessionAffinity: None
  type: LoadBalancer