apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: kube-apiserver-proxy-svc
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: false
  ports:
    - name: client
      port: 6443
      protocol: TCP
      targetPort: client
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer