---
apiVersion: v1
kind: Service
metadata:
  name: konnectivity-server-svc
  labels:
    app.kubernetes.io/name: konnectivity
spec:
  type: LoadBalancer
  ports:
  - port: 8131
    name: server
  - port: 8132
    name: agent
  - port: 8133
    name: admin
  - port: 8134
    name: health
  selector:
    app.kubernetes.io/name: konnectivity