---
apiVersion: v1
kind: Service
metadata:
  name: konnectivity-server-svc
  labels:
    app.kubernetes.io/name: konnectivity
spec:
  type: LoadBalancer
  ports:
  - port: 8090
    name: server
  - port: 8091
    name: agent
  - port: 8092
    name: admin
  - port: 8093
    name: health
  selector:
    app.kubernetes.io/name: konnectivity