---
apiVersion: v1
kind: Service
metadata:
  name: konnectivity-server-svc
  labels:
    app.kubernetes.io/name: konnectivity
spec:
  type: LoadBalancer
  ports:
  - port: 8131
    name: agentport
  selector:
    app.kubernetes.io/name: konnectivity