cat << EOF | kubectl apply -f -
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: example-vmcluster
spec:
  # Add fields here

  retentionPeriod: "1"
  vmstorage:
    replicaCount: 2
  vmselect:
    serviceSpec:
      spec:
        type: ClusterIP
    replicaCount: 2
  vminsert:
    replicaCount: 2
EOF