cat <<EOF | kubectl apply -f -
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: example-vmagent
spec:
  selectAllByDefault: true
  replicaCount: 1
  secrets:
      - pki-vmagent-client
  remoteWrite:
    - url: "http://vminsert-example-vmcluster:8480/insert/0/prometheus/api/v1/write"
EOF