# Source: kubernetes/templates/kubeadm-config.yaml
{{- $currentNamespace   := .Release.Namespace -}}
{{- $serviceApiServerLb := (lookup "v1" "Service" $currentNamespace "kube-apiserver-svc") }}
{{- $serviceApiServerIP := $serviceApiServerLb.status.loadBalancer.ingress }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-kubeadm-config
data:
  kubeadmcfg.yaml: |+
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterConfiguration
    controlPlaneEndpoint: {{ (first $serviceApiServerIP ).ip }}
    networking:
      serviceSubnet: "31.66.0.0/16"
    ---
    apiVersion: kubelet.config.k8s.io/v1beta1
    kind: KubeletConfiguration
    serverTLSBootstrap: true
    ---
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    kind: KubeProxyConfiguration
    mode: ipvs
    clientConnection:
    clusterCIDR: "31.66.0.0/16"
    metricsBindAddress: 0.0.0.0:10249