# Source: kubernetes/templates/kubeadm-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-kubeadm-config
data:
  kubeadmcfg.yaml: |+
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
controlPlaneEndpoint: 51.250.45.75:6443
networking:
  serviceSubnet: "31.66.0.0/16"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
serverTLSBootstrap: true
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: ipvs
clientConnection:
clusterCIDR: "31.66.0.0/16"
metricsBindAddress: 0.0.0.0:10249