---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "pki-cilium-operator-server-client"
spec:
  commonName: "system:cilium-operator"
  secretName: "pki-cilium-operator-client"
  duration: 8760h # 365d
  renewBefore: 4380h # 178d
  subject:
    organizations:
    - "system:masters"
  usages:
  - "signing"
  - "key encipherment"
  - "client auth"
  issuerRef:
    name: "issuer"
    kind: Issuer