---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "pki-metrics-server"
spec:
  commonName: "system:metrics-server"
  secretName: "pki-metrics-server"
  duration: 8760h # 365d
  renewBefore: 4380h # 178d
  subject:
    organizations:
    - "cluster-2"
  usages:
  - "signing"
  - "key encipherment"
  - "client auth"
  - "server auth"
  ipAddresses:
  dnsNames:
    - "localhost"
    - "metric-server-svc"
  issuerRef:
    name: "issuer"
    kind: Issuer