---
apiVersion: v1
kind: Service
metadata:
  name: kube-apiserver-svc
  labels:
    app.kubernetes.io/name: kube-apiserver
spec:
  type: ClusterIP
  ports:
  - port: 6443
    name: client
  selector:
    app.kubernetes.io/name: kube-apiserver