
{{- $baseName           := include "kube-apiserver.name" . -}}
{{- $selectorLabels     := include "kube-apiserver.selectorLabels" . -}}
{{- $commonLabels       := include "kube-apiserver.labels" . -}}
{{- $currentNamespace   := .Release.Namespace -}}

{{- $serviceApiServerLb := (lookup "v1" "Service" $currentNamespace "kube-apiserver-svc") }}
{{- $serviceApiServerIP := $serviceApiServerLb.status.loadBalancer.ingress }}

{{- with .Values.applications.kubeApiserver.Deployment }}
{{- $oidcStatus := .oidc.enable }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $baseName }}"
  labels:
    {{- $commonLabels | nindent 4 }}
  {{- with .metadata.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .metadata.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  replicas: {{ .replicas }}

  {{- with .strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  selector:
    matchLabels:
      {{- $selectorLabels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- $commonLabels | nindent 8 }}
      {{- with .metadata.labels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .metadata.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

    spec:

      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: {{ .affinity.topologyKey}}
                labelSelector:
                  matchLabels:
                    {{- $selectorLabels | nindent 20 }}

      automountServiceAccountToken: {{ .automountServiceAccountToken }}

      {{- with .containers.kubeApiserver }}
      containers:
        - name: {{ $baseName }}
          image: {{ .image }}
          imagePullPolicy: {{ .imagePullPolicy }}

          {{- with .entryPoint.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          args:
            - --proxy-client-cert-file=/pki/pki-{{ $baseName }}-proxy-client/tls.crt
            - --proxy-client-key-file=/pki/pki-{{ $baseName }}-proxy-client/tls.key
            - --requestheader-allowed-names={{ $baseName }}-proxy-client
            - --requestheader-client-ca-file=/pki/pki-{{ $baseName }}-proxy-client/ca.crt
            - --tls-cert-file=/pki/pki-{{ $baseName }}-server/tls.crt
            - --tls-private-key-file=/pki/pki-{{ $baseName }}-server/tls.key
            - --client-ca-file=/pki/pki-{{ $baseName }}-server/ca.crt
            - --etcd-cafile=/pki/pki-{{ $baseName }}-etcd-client/ca.crt
            - --etcd-certfile=/pki/pki-{{ $baseName }}-etcd-client/tls.crt
            - --etcd-keyfile=/pki/pki-{{ $baseName }}-etcd-client/tls.key
            - --kubelet-client-certificate=/pki/pki-{{ $baseName }}-kubelet-client/tls.crt
            - --kubelet-client-key=/pki/pki-{{ $baseName }}-kubelet-client/tls.key
            - --etcd-servers-overrides=/events#https://$(SVC_NAME)-events-svc-0:2379;https://$(SVC_NAME)-events-svc-1:2379;https://$(SVC_NAME)-events-svc-2:2379
            - --etcd-servers=https://$(SVC_NAME)-resources-svc-0:2379,https://$(SVC_NAME)-resources-svc-1:2379,https://$(SVC_NAME)-resources-svc-2:2379
          {{- range .ports  }}
            {{- if eq .name "client" }}
            - --secure-port={{- .containerPort }}
            {{- end }}
          {{- end }}
            - --service-cluster-ip-range=10.32.0.0/24
            - --advertise-address={{- (first $serviceApiServerIP).ip }}
          {{- if $oidcStatus }}
            - --oidc-issuer-url=https://keycloak.ingress.dobry-kot.ru/realms/terra-kube
            - --oidc-ca-file=/opt/bridge/pki/oidc/ca.crt
            - --oidc-client-id=kubernetes
            - --oidc-username-claim=email
            - --oidc-groups-claim=groups
            - --oidc-username-prefix=-
          {{- end }}
          {{- with .entryPoint.args }}
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          {{- with .envs }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          volumeMounts:
            - mountPath: /pki/pki-{{ $baseName }}-proxy-client
              name: pki-{{ $baseName }}-proxy-client
            - mountPath: /pki/pki-{{ $baseName }}-server
              name: pki-{{ $baseName }}-server
            - mountPath: /pki/pki-{{ $baseName }}-etcd-client
              name: pki-{{ $baseName }}-etcd-client
            - mountPath: /pki/pki-{{ $baseName }}-kubelet-client
              name: pki-{{ $baseName }}-kubelet-client
          {{- with .volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- end }}
      volumes:
        - secret:
            secretName: "pki-{{ $baseName }}-proxy-client"
          name: pki-{{ $baseName }}-proxy-client
        - secret:
            secretName: "pki-{{ $baseName }}-server"
          name: pki-{{ $baseName }}-server
        - secret:
            secretName: "pki-{{ $baseName }}-etcd-client"
          name: pki-{{ $baseName }}-etcd-client
        - secret:
            secretName: "pki-{{ $baseName }}-kubelet-client"
          name: pki-{{ $baseName }}-kubelet-client
      {{- with .volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
